name: Send notification on push
on: [push]

jobs:
  send-msg:
    runs-on: ubuntu-latest
    steps:
      - name: WeChat Work notification by text
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: text
          content: 广州今日天气：29度，大部分多云，降雨概率：60%

